"""The LangGraph agent.

    START → agent → (tool call?) → tools → agent → ... → END

Definition of done: pytest tests/test_agent.py
"""

from __future__ import annotations
import logging
from langchain_core.language_models import BaseChatModel
from langchain_core.messages import AIMessage, HumanMessage, SystemMessage, trim_messages
from langchain_core.tools import BaseTool
from langgraph.graph import END, START, StateGraph
from langgraph.prebuilt import ToolNode
from app.util.retry import with_retry
from app.agent.state import AgentState
from app.agent.security import (
    mask_input_pii,
    mask_output_pii,
    nemo_guardrails,
)
from app.config import get_settings
logger = logging.getLogger(__name__)

MAX_INPUT_CHARS = 8_000
RECURSION_LIMIT = 15


def build_graph(llm: BaseChatModel, tools: list[BaseTool], system_prompt: str, checkpointer=None):
    llm_with_tools = llm.bind_tools(tools)
    settings = get_settings()
    async def input_guardrail_node(state: AgentState):
        """Checks user input for PII and safety violations."""
        raw_user_text = HumanMessage(content=state["messages"][-1].content)

        # Step A: Apply PII Masking (e.g., Credit Cards)
        masked_text = mask_input_pii(raw_user_text.content)

        # Step B: Check Input Guardrails via NeMo
        is_safe = await nemo_guardrails.check_input(masked_text)

        if not is_safe:
            logger.warning("Input blocked by NeMo Guardrails.")
            return {
                "messages": [
                    AIMessage(content="I'm sorry, I can't help with that request.")
                ]
            }

        # If safe, keep moving (optionally update with masked text if modified)
        return {}
    async def output_guardrail_node(state: AgentState):
        """Validates the generated AI response for safety/hallucination before sending to user."""
        last_ai_message = state["messages"][-1]

        # Extract original user prompt if available in state
        user_text = ""
        for msg in reversed(state["messages"]):
            if isinstance(msg, HumanMessage):
                user_text = msg.content
                break

        # Check Output Guardrails via NeMo
        is_safe = await nemo_guardrails.check_output(
            assistant_text=last_ai_message.content,
            user_text=user_text
        )

        if not is_safe:
            logger.warning("Output blocked by NeMo Guardrails.")
            # Replace unsafe AI response with fallback string
            return {
                "messages": [
                    AIMessage(content="I'm sorry, I can't provide that response.")
                ]
            }
    def check_if_blocked(state: AgentState) -> str:
        last_msg = state["messages"][-1]
        # If the last message is an AIMessage generated by the input guardrail node, halt execution
        blocked_messages = "I'm sorry, I can't provide that response."
        if blocked_messages in last_msg:
            return "blocked"
        return "safe"


    async def agent_node(state: AgentState):
        def _token_count(msgs_or_msg):
            if isinstance(msgs_or_msg, list):
                return sum(len(str(getattr(m, 'content', m))) for m in msgs_or_msg)
            return len(str(getattr(msgs_or_msg, 'content', msgs_or_msg)))

        trimmed_messages = trim_messages(
            state["messages"],
            max_tokens=settings.history_max_messages * 500,
            strategy="last",
            token_counter=_token_count,
            start_on="human",
            include_system=False,
            allow_partial=False,
        )

        # Gemini API requires non-empty content for messages without tool calls
        sanitized_messages = []
        for msg in trimmed_messages:
            has_tools = bool(getattr(msg, "tool_calls", None))
            if not has_tools and (msg.content is None or str(msg.content).strip() == ""):
                msg = msg.model_copy(update={"content": " "})
            sanitized_messages.append(msg)

        messages = [SystemMessage(system_prompt)] + sanitized_messages
        response = await with_retry(
            lambda: llm_with_tools.ainvoke(messages),
            attempts=3,
            budget=12.0,
            label="gemini",
        )
        response = response.model_copy()
        response.id = None
        return {"messages": [response]}

    def after_agent(state: AgentState) -> str:
        """Tools must return to the agent; only its final answer is guarded."""
        last = state["messages"][-1]
        return "tools" if getattr(last, "tool_calls", None) else "output_guardrail"

    graph = StateGraph(AgentState)
    graph.add_node("input_guardrail", input_guardrail_node)
    graph.add_node("agent", agent_node)
    graph.add_node("output_guardrail", output_guardrail_node)
    graph.add_node("tools", ToolNode(tools))
    graph.add_edge(START, "input_guardrail")
    graph.add_conditional_edges("input_guardrail", check_if_blocked, {"blocked": END, "safe": "agent"})
    graph.add_conditional_edges("agent", after_agent, {"tools": "tools", "output_guardrail": "output_guardrail"})
    graph.add_edge("tools", "agent")
    graph.add_edge("output_guardrail", END)
    return graph.compile(checkpointer=checkpointer)


async def run_turn(
    graph,
    text: str,
    psid: str,
    thread_id: str | None = None,
    config_context: dict | None = None,
) -> str:
    tid = thread_id or psid
    user_text = text[:MAX_INPUT_CHARS]

    # 1. PII: mask credit cards in user input.
    user_text = mask_input_pii(user_text)

    configurable = {"thread_id": tid, "psid": psid}
    if config_context:
        configurable.update(config_context)

    # The graph owns NeMo input/output checks, so a message is not billed twice.
    result = await graph.ainvoke(
        {"messages": [HumanMessage(content=user_text)]},
        config={
            "configurable": configurable,
            "recursion_limit": RECURSION_LIMIT,
        },
    )

    content = result["messages"][-1].content
    if isinstance(content, list):
        reply = "".join(block.get("text", "") for block in content if isinstance(block, dict))
    else:
        reply = str(content)

    # Output rails ran in the graph's final node. Mask PII before delivery.
    reply = mask_output_pii(reply)

    return reply

