
models:
  - type: main
    engine: openai
    model: "openai/gpt-oss-safeguard-20b"
    parameters:
      base_url: "https://api.groq.com/openai/v1"
      temperature: 0.2
      max_tokens: 512
  - type: embeddings
    engine: FastEmbed
    model: "all-MiniLM-L6-v2"

rails:
  config:
    injection_detection:
      injections:
        - code
        - sqli
        - template
        - xss
      action: reject
  input:
    parallel: True 
    flows:
      - self check input
  output:
    flows:
      - self check output


